# -*- coding: utf-8 -*-
"""Partie 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S6hcUZPX7f1dFzGxDKb6Al6d7OyLs1an

2. Création de fonction comportant des modules de gestions des
exceptions
"""

def factorielle(n):
  if n == 0 : 
    return 1 
  if n == 1 : 
    return 1  
  elif n<0: 
    return print("insérer un nombre positif ")
  else : 
    return n*factorielle(n-1)

from math import*

n=int(input("Entre un entier: "))
if((isinstance(n, str))):
    raise Exception ("Erreur le nombre rentré est un string, réessayez !")
                  
if((isinstance(n, complex)) ):
                  
    raise Exception ("Erreur le nombre rentré est un complexe")
                  
if(n<0):
                  
    raise Exception("Erreur la variable est négative")
                  
if(n>1000):
                  
    raise Exception("Erreur la variable est trés grande")

print("Le factoriel de l'entier est :")                
factorielle(n)

