# -*- coding: utf-8 -*-
"""Partie 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vge0IW21yTdApE8PfHr7I7oDib1OXSeW

Question bonus
"""

